promotionComment: "<h6>Thanks for trying out the demo! Follow <a href='https://github.com/ubiquity'>Ubiquity on GitHub</a> and star <a href='https://github.com/ubiquity/devpool-directory'>this repo</a>. Your endorsement means the world to us and helps us grow!</h6><h6>We are excited to announce that the DevPool and UbiquiBot are now available to partners! Our ideal collaborators are globally distributed crypto-native organizations, who actively work on open source on GitHub, and excel in research & development. If you can introduce us to the repository maintainers in these types of companies, we have a special bonus in store for you!</h6>"

priceMultiplier: 4
issueCreatorMultiplier: 4
maxConcurrentAssigns: 2
paymentPermitMaxPrice: 1000

commentIncentives: true
assistivePricing: true
registerWalletWithVerification: false

incentives:
  comment:
    elements:
      code: 1
      img: 0
      h1: 1
      h2: 1
      h3: 1
      h4: 1
      h5: 1
      h6: 1
      li: 0.5
      a: 1
      blockquote: 0
    totals:
      word: 0.1

commandSettings:
  - name: start
    enabled: true
  - name: stop
    enabled: true
  - name: wallet
    enabled: true
  - name: payout
    enabled: true
  - name: multiplier
    enabled: true
  - name: query
    enabled: true
  - name: allow
    enabled: true
  - name: autopay
    enabled: true

enableAccessControl:
  label: false
  organization: false
